services:
  - type: web
    name: ems-frontend
    env: node
    build:
      rootDir: event-management-system/frontend
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: $API_BASE_URL
